### ISSUE TITLE
dependencies.json not generated on app load

### ISSUE THREAD

**Issue by apo5698** [apo5698/ags#17]
All dependencies are not available.

```ruby
2020-10-10T07:40:55.915808+00:00 app[web.1]: F, [2020-10-10T07:40:55.915678 #9] FATAL -- : [f3d29577-1f8e-45f2-8559-3737285dfe84]   
2020-10-10T07:40:55.915811+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] ActionView::Template::Error (No such file or directory @ rb_sysopen - /app/public/api/dependencies.json):
2020-10-10T07:40:55.915812+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     1: <div class="mb-2">
2020-10-10T07:40:55.915812+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     2:   <%= link_to('Reload', { controller: 'settings', action: 'reload' }, class: 'btn btn-secondary') %>
2020-10-10T07:40:55.915813+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     3:   <%= link_to('dependencies.json', DependenciesUtil.json, class: 'btn btn-secondary') %>
2020-10-10T07:40:55.915814+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     4: </div>
2020-10-10T07:40:55.915815+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     5: <table class="table table-hover">
2020-10-10T07:40:55.915815+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]     6:   <thead>
2020-10-10T07:40:55.915816+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84]   
2020-10-10T07:40:55.915816+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] app/lib/dependencies_util.rb:18:in `initialize'
2020-10-10T07:40:55.915817+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] app/lib/dependencies_util.rb:18:in `open'
2020-10-10T07:40:55.915817+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] app/lib/dependencies_util.rb:18:in `json'
2020-10-10T07:40:55.915818+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] app/views/settings/_dependencies.html.erb:3
2020-10-10T07:40:55.915818+00:00 app[web.1]: [f3d29577-1f8e-45f2-8559-3737285dfe84] app/views/settings/index.html.erb:19
```

**Comment by apo5698** [comment]
Heroku is not able to create folders and download files locally. See [Why are my file uploads missing/deleted? - Heroku Help](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted).

**Comment by apo5698** [comment]
`public/api` is still not created.
